# Generated by Django 5.1.3 on 2024-11-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_generos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('UF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uf')),
            ],
            options={
                'verbose_name_plural': 'Cidades',
            },
        ),
    ]
